### ISSUE TITLE
When I try to create speaker with audio I get RuntimeError: The batch dimension for log_probs must be 1 at the current version.

### ISSUE THREAD

**Issue by developer-yl** [edwko/OuteTTS#4]
How do I fix "RuntimeError: The batch dimension for log_probs must be 1 at the current version." when I use a speaker?

speaker = interface.create_speaker(
    "letssee.wav",
    "Let's see"
)

Sample audio and reference text:

[letssee.wav.zip](https://github.com/user-attachments/files/17624896/letssee.wav.zip)
"Let's see"

OS mac 14.7.1  python 3.11

**Comment by MDuc-ai** [comment]
Because the torch function F.forced_align only processes mono audio (only 1 channel) while your audio might be stereo audio. To solve this, you can convert your wav file to mono audio or change the code in your_env/lib/python3.*/outetts/v0_1/alignments.py at the line 92 to this
`alignments, scores = self._align(emission[0:1, :, :], tokenized_transcript)`

**Comment by MDuc-ai** [comment]
I've already opened a PR to fix this issue. Hope to get the approval soon.

**Comment by edwko** [comment]
I've implemented a fix for the mono audio issue. To get the latest version with this update, please run:

```bash
pip install outetts --upgrade --no-cache
```

This should resolve the issue.

**Comment by profitgrowinginnovator** [comment]
I was able to make it work with a short create_speaker wav so thanks for the help
