### ISSUE TITLE
Do you guys tested this on smart phones?

### ISSUE THREAD

**Issue by yashasnadigsyn** [edwko/OuteTTS#40]
I am thinking of deploying these on my android smart phone and whether it will be feasible? Any tips?

**Comment by edwko** [comment]
You can deploy the model itself using `llama.cpp` on Android. Here's an example from their docs: [Llama.cpp Android Example](https://github.com/ggerganov/llama.cpp/blob/master/docs/android.md). However, hosting the WavTokenizer on a mobile device could be challenging since it is based on PyTorch, you could look into projects like [PyTorch Executor](https://github.com/pytorch/executorch), which might be helpful for deploying PyTorch models.

**Comment by yashasnadigsyn** [comment]
Thank you!

**Comment by sl33pyC01E** [comment]
I came here to ask this^

I've tried loading it in termux and proot-ubuntu to no avail, but I am not a dev, just a hobbyist.

is there any more information available?

**Comment by yashasnadigsyn** [comment]
@sl33pyC01E You can just use llama.cpp and try to run it with GGUF. See the android example in the above comment.
