### ISSUE TITLE
Missing Question Inflection in Synthesized Speech

### ISSUE THREAD

**Issue by lxe** [edwko/OuteTTS#43]
It's currently not properly implementing rising intonation patterns for questions, resulting in all sentences having similar declarative prosody regardless of whether they are questions or statements. I suspect a phonemizer issue?

```python
output = interface.generate(
    text="Would you mind helping me carry these boxes upstairs to the attic?",
    temperature=0.1,
    repetition_penalty=1.1,
    max_length=4096,
    speaker=speaker
)
        
display(Audio(output.audio.cpu(), rate=output.sr))
```

https://github.com/user-attachments/assets/c3be30bf-1b4c-463c-8538-8e034e0b6de2

**Comment by edwko** [comment]
The current version only supports Latin characters and does cleanup in the backend, which is why the model ignores these patterns. You can see the text processing in this function: [process_text](https://github.com/edwko/OuteTTS/blob/8f5f510fa4683d62b03f951fc710937a9142f2b0/outetts/version/v1/prompt_processor.py#L39)

I'm planning to address this in a future release by adding support for special characters.
